import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { QueryProvider } from "@/shared/providers/query-provider";
import { ReactNode } from "react";
import { cookies } from "next/headers";
import { redirect } from "next/navigation";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

const interSans = Inter({
    variable: "--font-sans",
    subsets: ["latin"],
});

export default async function RootLayout({
    children,
}: {
    children: ReactNode;
}) {
    const cookieStore = await cookies();
    const token = cookieStore.get("auth_token");
    if (!token) {
        redirect("/login");
    }
    return (
        <html lang="en">
            <body
                className={`${interSans.variable} min-h-screen bg-background font-sans antialiased`}
            >
                <QueryProvider>{children}</QueryProvider>
            </body>
        </html>
    );
}
