import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { QueryProvider } from "@/shared/providers/query-provider";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

const interSans = Inter({
    variable: "--font-sans",
    subsets: ["latin"],
});

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="ru">
            <body
                className={`${interSans.variable} min-h-screen bg-background font-sans antialiased`}
            >
                <QueryProvider>{children}</QueryProvider>
            </body>
        </html>
    );
}
